import type {
    Alert,
    Bank,
    Evidence,
    GraphEdge,
    GraphNode,
    Investigation,
    KnowledgeEntry,
    Location,
    Person,
    Phone,
    ReportRecord,
    RiskAssessment,
    UPI,
} from "./types";

export const initialInvestigations: Investigation[] = [
    {
        id: "INV-2024-0001",
        type: "digital_arrest",
        title: "Digital Arrest Call Scam",
        status: "active",
        riskLevel: "critical",
        riskScore: 96,
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
        updatedAt: new Date(),
        citizenName: "Rajesh Kumar",
        phoneNumber: "+91-9876543210",
        description: "Victim received calls impersonating Police Commissioner.",
        source: "citizen",
        location: {
            city: "Mumbai",
            state: "Maharashtra",
            lat: 19.076,
            lng: 72.8777,
            risk: "critical",
            caseCount: 8,
            investigationIds: ["INV-2024-0001"],
        },
        evidenceIds: ["EV-1001"],
        alertIds: ["ALERT-1"],
        relatedEntityIds: ["phone_9876543210", "person_rajesh"],
        relatedCases: [],
        timeline: [
            {
                id: "TL-1",
                timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
                type: "complaint_filed",
                description: "Digital arrest complaint registered.",
                severity: "critical",
            },
            {
                id: "TL-2",
                timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
                type: "call_analyzed",
                description: "Audio analysis completed - 3 incoming calls detected.",
                severity: "high",
            },
        ],
        summary: "Police impersonation complaint escalated to active investigation.",
        assignedOfficer: "Inspector Sharma",
        riskHistory: [],
        aiOutputs: [],
        officerNotes: [],
        reportIds: [],
    },
    {
        id: "INV-2024-0002",
        type: "counterfeit",
        title: "Suspected Counterfeit Currency",
        status: "review",
        riskLevel: "high",
        riskScore: 89,
        createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
        updatedAt: new Date(),
        description: "Counterfeit currency notes identified.",
        source: "counterfeit",
        location: {
            city: "Delhi",
            state: "Delhi",
            lat: 28.6139,
            lng: 77.209,
            risk: "high",
            caseCount: 12,
            investigationIds: ["INV-2024-0002"],
        },
        evidenceIds: ["EV-2001"],
        alertIds: ["ALERT-2"],
        relatedEntityIds: ["bank_rbi"],
        relatedCases: [],
        timeline: [
            {
                id: "TL-3",
                timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
                type: "evidence_uploaded",
                description: "Currency images uploaded.",
                severity: "high",
            },
        ],
        summary: "Currency images submitted for authentication and template matching.",
        riskHistory: [],
        aiOutputs: [],
        officerNotes: [],
        reportIds: [],
    },
    {
        id: "INV-2024-0003",
        type: "banking_fraud",
        title: "UPI Transfer Fraud",
        status: "investigation",
        riskLevel: "high",
        riskScore: 82,
        createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
        updatedAt: new Date(),
        description: "UPI fraud - money transferred to unknown account.",
        source: "manual",
        location: {
            city: "Bangalore",
            state: "Karnataka",
            lat: 12.9716,
            lng: 77.5946,
            risk: "high",
            caseCount: 5,
            investigationIds: ["INV-2024-0003"],
        },
        evidenceIds: [],
        alertIds: ["ALERT-3"],
        relatedEntityIds: ["upi_scammer"],
        relatedCases: ["INV-2024-0004"],
        timeline: [],
        summary: "UPI transfer pattern linked to a broader fraud network.",
        riskHistory: [],
        aiOutputs: [],
        officerNotes: [],
        reportIds: [],
    },
    {
        id: "INV-2024-0004",
        type: "fraud_network",
        title: "Multi-State Fraud Network",
        status: "active",
        riskLevel: "critical",
        riskScore: 94,
        createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000),
        updatedAt: new Date(),
        description: "Network of 15 fraudsters operating across 3 states.",
        source: "manual",
        location: {
            city: "Kolkata",
            state: "West Bengal",
            lat: 22.5726,
            lng: 88.364,
            risk: "critical",
            caseCount: 18,
            investigationIds: ["INV-2024-0004"],
        },
        evidenceIds: [],
        alertIds: ["ALERT-4"],
        relatedEntityIds: ["phone_9988776655", "upi_scammer"],
        relatedCases: ["INV-2024-0003"],
        timeline: [],
        summary: "Cross-linked entities indicate an active criminal network.",
        riskHistory: [],
        aiOutputs: [],
        officerNotes: [],
        reportIds: [],
    },
];

export const initialAlerts: Alert[] = [
    {
        id: "ALERT-1",
        title: "Suspicious Call Pattern Detected",
        description: "High frequency calls from 3 numbers to a single recipient.",
        timestamp: new Date(Date.now() - 2 * 60 * 1000),
        severity: "critical",
        caseId: "INV-2024-0001",
        resolved: false,
        source: "digital_arrest",
    },
    {
        id: "ALERT-2",
        title: "Counterfeit Currency Identified",
        description: "RBI template mismatch detected in uploaded image.",
        timestamp: new Date(Date.now() - 8 * 60 * 1000),
        severity: "high",
        caseId: "INV-2024-0002",
        resolved: false,
        source: "counterfeit",
    },
    {
        id: "ALERT-3",
        title: "Network Anomaly Detected",
        description: "New UPI-based money transfer network identified.",
        timestamp: new Date(Date.now() - 15 * 60 * 1000),
        severity: "high",
        caseId: "INV-2024-0003",
        resolved: false,
        source: "engine",
    },
];

export const initialPeople: Person[] = [
    {
        id: "person_rajesh",
        name: "Rajesh Kumar",
        riskScore: 95,
        investigationIds: ["INV-2024-0001"],
    },
    {
        id: "person_priya",
        name: "Priya Singh",
        riskScore: 71,
        investigationIds: ["INV-2024-0003"],
    },
];

export const initialPhones: Phone[] = [
    {
        id: "phone_9876543210",
        number: "+91-9876543210",
        riskScore: 88,
        investigationIds: ["INV-2024-0001"],
        entityIds: ["person_rajesh", "upi_scammer"],
    },
    {
        id: "phone_9988776655",
        number: "+91-9988776655",
        riskScore: 92,
        investigationIds: ["INV-2024-0004"],
        entityIds: ["upi_scammer", "bank_icici"],
    },
];

export const initialUpis: UPI[] = [
    {
        id: "upi_scammer",
        handle: "scammer.upi@bank",
        riskScore: 98,
        investigationIds: ["INV-2024-0003", "INV-2024-0004"],
        entityIds: ["phone_9988776655", "bank_icici"],
    },
];

export const initialBanks: Bank[] = [
    {
        id: "bank_icici",
        name: "ICICI Account",
        riskScore: 90,
        investigationIds: ["INV-2024-0003"],
        entityIds: ["upi_scammer"],
    },
];

export const initialLocations: Location[] = [
    {
        city: "Mumbai",
        state: "Maharashtra",
        lat: 19.076,
        lng: 72.8777,
        risk: "critical",
        caseCount: 8,
        investigationIds: ["INV-2024-0001"],
    },
    {
        city: "Delhi",
        state: "Delhi",
        lat: 28.6139,
        lng: 77.209,
        risk: "high",
        caseCount: 12,
        investigationIds: ["INV-2024-0002"],
    },
    {
        city: "Bangalore",
        state: "Karnataka",
        lat: 12.9716,
        lng: 77.5946,
        risk: "high",
        caseCount: 5,
        investigationIds: ["INV-2024-0003"],
    },
    {
        city: "Kolkata",
        state: "West Bengal",
        lat: 22.5726,
        lng: 88.364,
        risk: "critical",
        caseCount: 18,
        investigationIds: ["INV-2024-0004"],
    },
    {
        city: "Pune",
        state: "Maharashtra",
        lat: 18.5204,
        lng: 73.8567,
        risk: "medium",
        caseCount: 3,
        investigationIds: [],
    },
    {
        city: "Hyderabad",
        state: "Telangana",
        lat: 17.385,
        lng: 78.4867,
        risk: "high",
        caseCount: 7,
        investigationIds: [],
    },
];

export const initialGraphNodes: GraphNode[] = [
    {
        id: "person_rajesh",
        label: "Rajesh Kumar",
        type: "citizen",
        riskScore: 95,
        connections: 5,
        investigationIds: ["INV-2024-0001"],
    },
    {
        id: "phone_9876543210",
        label: "+91-9876543210",
        type: "phone",
        riskScore: 88,
        connections: 8,
        investigationIds: ["INV-2024-0001"],
    },
    {
        id: "phone_9988776655",
        label: "+91-9988776655",
        type: "phone",
        riskScore: 92,
        connections: 12,
        investigationIds: ["INV-2024-0004"],
    },
    {
        id: "upi_scammer",
        label: "scammer.upi@bank",
        type: "upi",
        riskScore: 98,
        connections: 15,
        investigationIds: ["INV-2024-0003", "INV-2024-0004"],
    },
    {
        id: "device_imei",
        label: "Device A (IMEI: 12345)",
        type: "device",
        riskScore: 85,
        connections: 6,
        investigationIds: ["INV-2024-0004"],
    },
    {
        id: "location_mumbai",
        label: "Mumbai HQ",
        type: "location",
        riskScore: 87,
        connections: 10,
        investigationIds: ["INV-2024-0001"],
    },
    {
        id: "bank_icici",
        label: "ICICI Account",
        type: "bank",
        riskScore: 90,
        connections: 8,
        investigationIds: ["INV-2024-0003"],
    },
];

export const initialGraphEdges: GraphEdge[] = [
    { source: "person_rajesh", target: "phone_9876543210", type: "owns", weight: 1, investigationId: "INV-2024-0001" },
    { source: "phone_9876543210", target: "phone_9988776655", type: "calls", weight: 15, investigationId: "INV-2024-0004" },
    { source: "phone_9988776655", target: "upi_scammer", type: "transfers_to", weight: 8, investigationId: "INV-2024-0004" },
    { source: "upi_scammer", target: "device_imei", type: "accessed_from", weight: 1, investigationId: "INV-2024-0004" },
    { source: "phone_9876543210", target: "location_mumbai", type: "located_at", weight: 1, investigationId: "INV-2024-0001" },
    { source: "upi_scammer", target: "bank_icici", type: "linked_to", weight: 1, investigationId: "INV-2024-0003" },
];

export const initialRiskAssessments: RiskAssessment[] = [
    { investigationId: "INV-2024-0001", score: 96, level: "critical", factors: ["government impersonation", "urgent payment demand"], updatedAt: new Date() },
    { investigationId: "INV-2024-0002", score: 89, level: "high", factors: ["template mismatch", "serial anomalies"], updatedAt: new Date() },
    { investigationId: "INV-2024-0003", score: 82, level: "high", factors: ["UPI transfer chain", "unknown recipient"], updatedAt: new Date() },
];

export const initialReports: ReportRecord[] = [];

export const initialKnowledgeBase: KnowledgeEntry[] = [
    { id: "kb-1", title: "Digital Arrest Pattern", category: "Scam Pattern", content: "Government impersonation scams use urgency, secrecy, and account freezing threats.", tags: ["digital arrest", "police impersonation", "urgent"] },
    { id: "kb-2", title: "Counterfeit RBI Checklist", category: "Forensics", content: "Verify watermark, security thread, microtext, and serial consistency.", tags: ["counterfeit", "rbi", "forensics"] },
    { id: "kb-3", title: "UPI Safety Checklist", category: "Payments", content: "Validate handles, inspect QR codes, and never trust pressure-based transfer requests.", tags: ["upi", "banking fraud", "payments"] },
];
